= Training and Data Mining Assertion
:toc: macro
:toc-title:
:sectanchors:
:sectnums:

The *link:https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html[C2PA technical specification]* allows actors in a workflow to make cryptographically signed assertions about the produced C2PA asset.

The *training and data mining assertion* enables a human actor to provide a C2PA Manifest Consumer information about whether an asset with C2PA metadata may be used as part of a data mining or AI/ML training workflow.

*Version 1.1 Draft 22 July 2024* · xref:_version_history[]

IMPORTANT: The Creator Assertions Working Group expects to release an update to this specification late in 2024. This page is the working draft of that update. Until that time, implementers should refer to the xref:1.0@training-and-data-mining:ROOT:index.adoc[1.0 version of this specification].

[#maintainers]
*Maintainers:*

* mailto:scouten@adobe.com[Eric Scouten] (https://adobe.com[Adobe])

include::partial$license.adoc[]
include::partial$contributing.adoc[]
include::partial$foreword.adoc[]
include::partial$toc.adoc[]

== Introduction

_This section is non-normative._

=== Scope

IMPORTANT: For purposes of the Community Specification License, the link:https://github.com/creator-assertions/training-and-data-mining-assertion/blob/main/scope.md[`scope.md` document] at the root of this project’s GitHub repository is the governing document of this specification’s scope.

== Normative references

* https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html[C2PA technical specification, version 2.0]

== Assertion definition

=== Overview

This assertion enables a human actor to provide a Manifest Consumer information about whether the asset may be used as part of a data mining or AI/ML training workflow. This is expressed in the assertion through a map of one or more `training-mining-entries`. Each entry describes whether its use is `allowed`, `notAllowed`, or `constrained`.

There are five pre-defined entries:

`cawg.data_mining`::
Can any text or data content be extracted from the asset for purposes of determining “patterns, trends, and correlations.”
+
NOTE: This would include images containing text, where the text could be extracted via OCR.

`cawg.ai_inference`::
Can the asset be used as input to a trained AI/ML model for the purposes of _inferring_ a result.

`cawg.ai_generative_training`::
Can the asset be used as training data to an AI/ML model that could generate assets.

`cawg.ai_training`::
Can the asset be used as data to train non-generative AI/ML models, such as those used for classification, object detection, etc.

[NOTE]
====
`cawg.ai_generative_training` and `cawg.ai_training` are separate values because generative AI training enables new assets to be created from training assets, while other types, such as object detection, do not.
====

`cawg.social_media`::
Can the asset be shared on social media platforms, groups, and messenger services. For this entry, the meaning of the possible values is defined as follows:
- `allowed`: The distribution of this asset is not limited in any way. It may be shared and/or distributed in any other way on all social media platforms, in all groups, messenger services, websites, etc. without any restrictions.
- `notAllowed`: The distribution of this asset is explicitly not allowed. It may not be shared and/or distributed in any other way on any social media platform, messenger service, website, etc. Social media platforms, websites, messenger services, etc. should automatically and instantly reject the upload of any such asset. 
- `constrained`: The distribution of this asset is restricted to a private scope. It may only be shared and/or distributed on private profiles and/or private groups on social media platforms, private websites, and/or private messenger groups. It may not be shared and/or distributed in any way that allows for public access. Social media platforms, websites, messenger services, etc. should automatically and instantly reject sharing such an asset outside the defined private scope.

In addition to the pre-defined entries, a claim generator may also add their own custom keys, provided that they conform to the same syntax for _custom labels_ as defined in link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_labels++[Section 6.2, “Labels,” of the C2PA Technical Specification]. Labels beginning with the prefix `cawg.` are reserved for use in future versions of this specification and MUST NOT be assigned by any other claim generator.

The value of `constrained` implies that permission is not unconditionally granted for this usage. Consumers of this content that wish to use the content in this way may wish to contact the actor which is the rights holder, author, or signer to get more info or obtain permission. In the absence of additional information, `constrained` shall be treated as equivalent to `notAllowed`. More details on the constraints may be provided in the `constraints_info` text field.

NOTE: Some possible things that could be put into `constraints_info` include a well-known description of a license (e.g., link:https://creativecommons.org/[Creative Commons]), a URL to a policy file, or just some free text.

A training and data mining assertion SHALL have a label of `cawg.training-mining`.

[WARNING]
.Notice to implementers of previous (C2PA 1.x) definition of this assertion
====
Implementers who are transitioning from the earlier definition of this assertion should pay special attention to label names.

The link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_training_and_data_mining++[training and data mining assertion as defined in version 1.4 of the C2PA technical specification] used labels with the prefix `c2pa.` for the assertion itself and for the pre-defined `training-mining-map` entries.

This specification is not a product of the C2PA itself, so it can not use the `c2pa.` prefix. Therefore, though structurally similar to the C2PA 1.x definition, the labels have been changed to `cawg.` in this specification.
====

=== Schema and example

The https://datatracker.ietf.org/doc/html/rfc8610[CDDL Definition] for this type is:

[source,cddl]
----
include::../partials/schemas/cddl/training-mining.cddl[]
----

An example in CBOR Diagnostic Format (`.cbordiag`) is shown below:

[source,json]
----
include::../partials/schemas/cddl/examples/training-mining.cbordiag[]
----

include::partial$version-history.adoc[]
